version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      time: "11:00"

  # Maintain dependencies for Composer
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      time: "07:00"
    open-pull-requests-limit: 100
    versioning-strategy: lockfile-only
    ignore:
      - dependency-name: doctrine/dbal
        versions:
          - ">= 2.10.a"
          - "< 2.11"
 
   # Maintain dependencies for npm
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "07:00"
    open-pull-requests-limit: 100
    versioning-strategy: lockfile-only
