language: php

php:
  - 7.1

services:
  - mysql
  - postgresql
env:
  - DB=mysql
  - DB=postgres

before_script:
  - sh -c "if [ '$DB' = 'postgres' ]; then cp .env.postgres.travis .env; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then cp .env.mysql.travis .env; fi"
  - sh -c "if [ '$DB' = 'postgres' ]; then psql -c 'CREATE DATABASE monica;' -U postgres; fi"
  - sh -c "if [ '$DB' = 'mysql' ]; then mysql -e 'CREATE DATABASE monica;'; fi"
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit
