sudo: required
language: php

php:
  - 7.1

services:
  - mysql

addons:
  sonarcloud:
    organization: "monicahq"
# Add a SONAR_TOKEN variable in the travis Repository Settings - see https://docs.travis-ci.com/user/sonarcloud/
#    token:
#      secure: ""
    branches:
        - master
        - sonar-analyser

jdk:
  - oraclejdk8

before_script:
  - cp .env.travis .env
  - mysql -e 'create database monica;'
  - composer self-update
  - composer install --no-interaction

script:
  - php artisan migrate --env=testing --no-interaction -vvv
  - php artisan db:seed --env=testing --no-interaction -vvv
  - vendor/bin/phpunit --log-junit phpunit.result.xml --coverage-clover phpunit.coverage.xml
  - sonar-scanner -Dsonar.php.tests.reportPath=phpunit.result.xml -Dsonar.php.coverage.reportPaths=phpunit.coverage.xml

cache:
  directories:
    - '$HOME/.sonar/cache'
