# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1-node

    working_directory: ~/monica

    steps:
      - checkout
      - run:
          name: Install extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y zlib1g-dev libicu-dev g++
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install zip intl bcmath
      - run:
          name: Prepare environment
          command: |
            cp scripts/tests/.env.mysql.travis .env

    ## COMPOSER
      - run: sudo composer self-update
      - restore_cache:
          keys:
          - composer-v2-{{ checksum "composer.json" }}
          - composer-v2-
      - run: composer install --no-interaction --no-suggest --ignore-platform-reqs
      - save_cache:
          key: composer-v2-{{ checksum "composer.json" }}
          paths:
            - vendor

    ## NODE.JS
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package.json" }}
            - node-v2-
      - run: yarn install
      - save_cache:
          key: node-v2-{{ checksum "package.json" }}
          paths:
            - node_modules

  # Build js and css assets
      - run:
          name: Build assets
          command: |
            php artisan lang:generate
            yarn run production
      - save_cache:
          key: assets-v2-{{ .Revision }}
          paths:
            - public/mix-manifest.json
            - public/css
            - public/fonts
            - public/js

  tests:
    docker:
      - image: circleci/php:7.1-node-browsers
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: monica

    working_directory: ~/monica

    steps:
      - checkout
      - run:
          name: Install extensions
          command: |
            sudo apt-get update
            sudo apt-get install -y zlib1g-dev libicu-dev g++ mysql-client
            sudo docker-php-ext-configure intl
            sudo docker-php-ext-install zip intl bcmath pdo_mysql
      - run:
          name: Prepare environment
          command: |
            mkdir -p results/coverage
            cp scripts/tests/.env.mysql.travis .env

    ## COMPOSER
      - restore_cache:
          keys:
          - composer-v2-{{ checksum "composer.json" }}
          - composer-v2-
    ## NODE.JS
      - restore_cache:
          keys:
            - node-v2-{{ checksum "package.json" }}
            - node-v2-
    ## ASSETS
      - restore_cache:
          keys:
            - assets-v2-{{ .Revision }}
            - assets-v2

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 120s
      - run:
          name: Prepare database
          command: |
            php artisan migrate --env=testing --no-interaction -vvv
            php artisan db:seed --env=testing --no-interaction -vvv

  # Run unit tests
      - run:
          name: Run unit tests
          command: vendor/bin/phpunit -c phpunit.xml
      - store_test_results:
          path: results
      - store_artifacts:
          path: results

  # Reports
#      - run: if [[ "$COVERAGE" == "1" ]]; then scripts/tests/travis-sonar.sh; fi


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - tests:
          requires:
            - build
