jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml

  - bash: |
      sudo composer self-update
      yarn global add greenkeeper-lockfile@1
    displayName: 'Prepare environment'

  ## COMPOSER
#  - task: DownloadPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: $(System.DefaultWorkingDirectory)
  - bash: |
      composer global require hirak/prestissimo
      composer install --no-interaction --no-suggest --ignore-platform-reqs
    displayName: 'composer install'
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: '~/.composer/cache/'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'vendor'
      targetPath: 'vendor'

  ## NODE.JS
  - bash: yarn inst
    displayName: 'yarn install'

  # Update js and css assets eventually
  - bash: yarn lint
    displayName: 'Check js and vue lint'
  - bash: scripts/ci/update-assets.sh
    displayName: 'Update assets'
