jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - bash: |
      sudo update-alternatives --set php /usr/bin/php$(phpVersion)
      sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
      sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
      sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
      sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
      php -version
    displayName: 'Use PHP version $(phpVersion)'

  - template: prepare-environment-step.yml

  - bash: |
      sudo composer self-update
      yarn global add greenkeeper-lockfile@1
    displayName: 'Prepare environment'

  ## COMPOSER
#  - task: DownloadPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: $(System.DefaultWorkingDirectory)
  - bash: |
      composer global require hirak/prestissimo
      composer install --no-interaction --no-suggest --ignore-platform-reqs
    displayName: 'composer install'
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: '~/.composer/cache/'
  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'artifactComposer'
      targetPath: 'vendor'

  ## NODE.JS
  - bash: yarn inst
    displayName: 'yarn install'

  # Update js and css assets eventually
  - bash: yarn lint
    displayName: 'Check js and vue lint'
  - bash: scripts/ci/update-assets.sh
    displayName: 'Update assets'
