jobs:
- job: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml

  ## COMPOSER
#  - task: DownloadPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: $(System.DefaultWorkingDirectory)
  - template: restore-artifacts-step.yml

#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'artifactName'
#      targetPath: '~/.composer/cache/'
#  - task: PublishPipelineArtifact@0
#    inputs:
#      artifactName: 'vendor'
#      targetPath: 'vendor'

- job: build_assets
  dependsOn: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml
  - template: restore-artifacts-step.yml

  - bash: |
      yarn global add greenkeeper-lockfile@1
    displayName: 'Prepare environment'

  ## NODE.JS
  - bash: yarn inst
    displayName: 'yarn install'

  # Update js and css assets eventually
  - bash: yarn lint
    displayName: 'Check js and vue lint'
  - bash: scripts/ci/update-assets.sh
    displayName: 'Update assets'
