jobs:
- job: build
  dependsOn: build
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: prepare-environment-step.yml
  - template: composer-install-step.yml

  - bash: |
      yarn global add greenkeeper-lockfile@1
    displayName: 'Prepare environment'

  ## NODE.JS
  - bash: yarn inst
    displayName: 'yarn install'

  # Update js and css assets eventually
  - bash: yarn lint
    displayName: 'Check js and vue lint'
  - bash: scripts/ci/update-assets.sh
    displayName: 'Update assets'
