steps:
- bash: |
    scripts/ci/rebase.sh
    echo "SONAR_TOKEN1=`echo ${SONAR_TOKEN1} | head -c 3`"
    echo "SONAR_TOKEN2=`echo ${SONAR_TOKEN2} | head -c 3`"
    echo "SONAR_TOKEN3=`echo ${SONAR_TOKEN3} | head -c 3`"
    echo "SONAAR_TOKEN1=`echo ${SONAAR_TOKEN1} | head -c 3`"
    echo "SONAAR_TOKEN2=`echo ${SONAAR_TOKEN2} | head -c 3`"
    echo "SONAAR_TOKEN3=`echo ${SONAAR_TOKEN3} | head -c 3`"
  displayName: 'Rebase sources'
  env:
    SONAR_TOKEN1: $SONAR_TOKEN
    SONAR_TOKEN2: $(SONAR_TOKEN)
    SONAR_TOKEN3: ${SONAR_TOKEN}
    SONAAR_TOKEN1: $Sonaar.Token
    SONAAR_TOKEN2: $(Sonaar.Token)
    SONAAR_TOKEN3: ${Sonaar.Token}

- bash: |
    sudo update-alternatives --set php /usr/bin/php$(phpVersion)
    sudo update-alternatives --set phar /usr/bin/phar$(phpVersion)
    sudo update-alternatives --set phpdbg /usr/bin/phpdbg$(phpVersion)
    sudo update-alternatives --set php-cgi /usr/bin/php-cgi$(phpVersion)
    sudo update-alternatives --set phar.phar /usr/bin/phar.phar$(phpVersion)
    php -version
  displayName: 'Set php version'

- bash: |
    mkdir -p results/coverage
    sed 's/DB_TEST_PASSWORD=/DB_TEST_PASSWORD=root/' scripts/tests/.env.mysql > .env
    touch .sentry-release
  displayName: 'Prepare environment'
