name: Build assets

on:
  pull_request:
    types: [opened, synchronize, reopened]

concurrency:
  group: Build assets ${{ github.ref }}
  cancel-in-progress: true

jobs:
  statics:
    uses: monicahq/workflows/.github/workflows/build_assets.yml@init
    with:
      node-version: 18
