name: Static analysis

on:
  push:
    branches-ignore:
      - '3.x*'

jobs:
  psalm:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer files
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs

      - name: Run psalm
        run: vendor/bin/psalm --output-format=github --shepherd

  phpstan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ['7.4']

    steps:
      - uses: actions/checkout@v1

      - name: Setup PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer files
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
            ${{ runner.os }}-composer-

      - name: Install dependencies
        run: composer install --no-interaction --no-suggest --ignore-platform-reqs

      - name: Run phpstan
        run: vendor/bin/phpstan analyse
